datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/travelbd
  username: root
  password: root

hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect
  format_sql: true
  show_sql: true